//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazzasBazaarExternalServiceProxyWCF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/BazzasBazaar.Service")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvailableProductCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvailableProductCount {
            get {
                return this.AvailableProductCountField;
            }
            set {
                if ((this.AvailableProductCountField.Equals(value) != true)) {
                    this.AvailableProductCountField = value;
                    this.RaisePropertyChanged("AvailableProductCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/BazzasBazaar.Service")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ExpectedRestockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InStockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceForOneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceForTenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ean {
            get {
                return this.EanField;
            }
            set {
                if ((object.ReferenceEquals(this.EanField, value) != true)) {
                    this.EanField = value;
                    this.RaisePropertyChanged("Ean");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpectedRestock {
            get {
                return this.ExpectedRestockField;
            }
            set {
                if ((this.ExpectedRestockField.Equals(value) != true)) {
                    this.ExpectedRestockField = value;
                    this.RaisePropertyChanged("ExpectedRestock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InStock {
            get {
                return this.InStockField;
            }
            set {
                if ((this.InStockField.Equals(value) != true)) {
                    this.InStockField = value;
                    this.RaisePropertyChanged("InStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PriceForOne {
            get {
                return this.PriceForOneField;
            }
            set {
                if ((this.PriceForOneField.Equals(value) != true)) {
                    this.PriceForOneField = value;
                    this.RaisePropertyChanged("PriceForOne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PriceForTen {
            get {
                return this.PriceForTenField;
            }
            set {
                if ((this.PriceForTenField.Equals(value) != true)) {
                    this.PriceForTenField = value;
                    this.RaisePropertyChanged("PriceForTen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/BazzasBazaar.Service")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductEanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime WhenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductEan {
            get {
                return this.ProductEanField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductEanField, value) != true)) {
                    this.ProductEanField = value;
                    this.RaisePropertyChanged("ProductEan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalPrice {
            get {
                return this.TotalPriceField;
            }
            set {
                if ((this.TotalPriceField.Equals(value) != true)) {
                    this.TotalPriceField = value;
                    this.RaisePropertyChanged("TotalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime When {
            get {
                return this.WhenField;
            }
            set {
                if ((this.WhenField.Equals(value) != true)) {
                    this.WhenField = value;
                    this.RaisePropertyChanged("When");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IStore")]
    public interface IStore {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetAllCategories", ReplyAction="http://tempuri.org/IStore/GetAllCategoriesResponse")]
        BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Category[] GetAllCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetAllCategories", ReplyAction="http://tempuri.org/IStore/GetAllCategoriesResponse")]
        System.Threading.Tasks.Task<BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Category[]> GetAllCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetCategoryById", ReplyAction="http://tempuri.org/IStore/GetCategoryByIdResponse")]
        BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Category GetCategoryById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetCategoryById", ReplyAction="http://tempuri.org/IStore/GetCategoryByIdResponse")]
        System.Threading.Tasks.Task<BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Category> GetCategoryByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetFilteredProducts", ReplyAction="http://tempuri.org/IStore/GetFilteredProductsResponse")]
        BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Product[] GetFilteredProducts(System.Nullable<int> categoryId, string categoryName, System.Nullable<double> minPrice, System.Nullable<double> maxPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetFilteredProducts", ReplyAction="http://tempuri.org/IStore/GetFilteredProductsResponse")]
        System.Threading.Tasks.Task<BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Product[]> GetFilteredProductsAsync(System.Nullable<int> categoryId, string categoryName, System.Nullable<double> minPrice, System.Nullable<double> maxPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetProductById", ReplyAction="http://tempuri.org/IStore/GetProductByIdResponse")]
        BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Product GetProductById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetProductById", ReplyAction="http://tempuri.org/IStore/GetProductByIdResponse")]
        System.Threading.Tasks.Task<BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Product> GetProductByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetOrderById", ReplyAction="http://tempuri.org/IStore/GetOrderByIdResponse")]
        BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Order GetOrderById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetOrderById", ReplyAction="http://tempuri.org/IStore/GetOrderByIdResponse")]
        System.Threading.Tasks.Task<BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Order> GetOrderByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/CreateOrder", ReplyAction="http://tempuri.org/IStore/CreateOrderResponse")]
        BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Order CreateOrder(string accountName, string cardNumber, int productId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/CreateOrder", ReplyAction="http://tempuri.org/IStore/CreateOrderResponse")]
        System.Threading.Tasks.Task<BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Order> CreateOrderAsync(string accountName, string cardNumber, int productId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/CancelOrderById", ReplyAction="http://tempuri.org/IStore/CancelOrderByIdResponse")]
        bool CancelOrderById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/CancelOrderById", ReplyAction="http://tempuri.org/IStore/CancelOrderByIdResponse")]
        System.Threading.Tasks.Task<bool> CancelOrderByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStoreChannel : BazzasBazaarExternalServiceProxyWCF.ServiceReference1.IStore, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreClient : System.ServiceModel.ClientBase<BazzasBazaarExternalServiceProxyWCF.ServiceReference1.IStore>, BazzasBazaarExternalServiceProxyWCF.ServiceReference1.IStore {
        
        public StoreClient() {
        }
        
        public StoreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StoreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Category[] GetAllCategories() {
            return base.Channel.GetAllCategories();
        }
        
        public System.Threading.Tasks.Task<BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Category[]> GetAllCategoriesAsync() {
            return base.Channel.GetAllCategoriesAsync();
        }
        
        public BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Category GetCategoryById(int id) {
            return base.Channel.GetCategoryById(id);
        }
        
        public System.Threading.Tasks.Task<BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Category> GetCategoryByIdAsync(int id) {
            return base.Channel.GetCategoryByIdAsync(id);
        }
        
        public BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Product[] GetFilteredProducts(System.Nullable<int> categoryId, string categoryName, System.Nullable<double> minPrice, System.Nullable<double> maxPrice) {
            return base.Channel.GetFilteredProducts(categoryId, categoryName, minPrice, maxPrice);
        }
        
        public System.Threading.Tasks.Task<BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Product[]> GetFilteredProductsAsync(System.Nullable<int> categoryId, string categoryName, System.Nullable<double> minPrice, System.Nullable<double> maxPrice) {
            return base.Channel.GetFilteredProductsAsync(categoryId, categoryName, minPrice, maxPrice);
        }
        
        public BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Product GetProductById(int id) {
            return base.Channel.GetProductById(id);
        }
        
        public System.Threading.Tasks.Task<BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Product> GetProductByIdAsync(int id) {
            return base.Channel.GetProductByIdAsync(id);
        }
        
        public BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Order GetOrderById(int id) {
            return base.Channel.GetOrderById(id);
        }
        
        public System.Threading.Tasks.Task<BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Order> GetOrderByIdAsync(int id) {
            return base.Channel.GetOrderByIdAsync(id);
        }
        
        public BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Order CreateOrder(string accountName, string cardNumber, int productId, int quantity) {
            return base.Channel.CreateOrder(accountName, cardNumber, productId, quantity);
        }
        
        public System.Threading.Tasks.Task<BazzasBazaarExternalServiceProxyWCF.ServiceReference1.Order> CreateOrderAsync(string accountName, string cardNumber, int productId, int quantity) {
            return base.Channel.CreateOrderAsync(accountName, cardNumber, productId, quantity);
        }
        
        public bool CancelOrderById(int id) {
            return base.Channel.CancelOrderById(id);
        }
        
        public System.Threading.Tasks.Task<bool> CancelOrderByIdAsync(int id) {
            return base.Channel.CancelOrderByIdAsync(id);
        }
    }
}
